languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Josh Aarons"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My personal website"

[params.author]
  # name = "Josh Aarons"
  # image = "img/author.jpg"
  # headline = "Department of Economics -- University of California San Diego "
  # bio = "Welcome to my personal webpage. I am currently a PhD candidate at UC San Diego. I am an applied microeconomist who studies environmental economics."
  # links = [
  #   { email = "mailto:jaarons@ucsd.edu" },
  #   { github = "https://github.com/jaarons-econ" },
  # ]
