languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Joshua Aarons"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My personal website"

[params.author]
  name = "Joshua Aarons"
  image = "img/author.jpg"
  headline = "Department of Economics -- University of California San Diego "

  links = [
    { email = "mailto:jaarons@ucsd.edu" },
    { github = "https://github.com/jaarons-econ" },
  ]
